// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BusinessStack  string
	Businesses     string
	Migrations     string
	PasswordResets string
	StackTag       string
	Stacks         string
	Tags           string
	UserBusiness   string
	Users          string
}{
	BusinessStack:  "business_stack",
	Businesses:     "businesses",
	Migrations:     "migrations",
	PasswordResets: "password_resets",
	StackTag:       "stack_tag",
	Stacks:         "stacks",
	Tags:           "tags",
	UserBusiness:   "user_business",
	Users:          "users",
}
