// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Business      string
	BusinessStack string
	PasswordReset string
	Stack         string
	StackTag      string
	Tag           string
	User          string
}{
	Business:      "business",
	BusinessStack: "business_stack",
	PasswordReset: "password_reset",
	Stack:         "stack",
	StackTag:      "stack_tag",
	Tag:           "tag",
	User:          "user",
}
